name: Validate PR and Issues

on:
  pull_request:
    types: [opened, edited, synchronize]
  issues:
    types: [opened, edited]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate PR title and body
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request || {};
            const title = pr.title || '';
            const body = pr.body || '';
            const regex = /^(feat|fix|docs|chore|refactor|perf|test|ci): .+/;
            if (!regex.test(title)) {
              core.setFailed('PR title must follow conventional commits (e.g. "feat: add xyz").');
            }
            if (!body || body.trim().length === 0) {
              core.setFailed('PR body is required. Please provide a summary, changes and testing steps.');
            }

      - name: Validate issue body via script
        if: github.event_name == 'issues'
        run: |
          node .github/scripts/validate-issue.js <<< "${{ toJson(github.event.issue.body) }}"

      - name: Validate issue template
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue || null;
            if (!issue) return;
            const required = ['**Describe the bug**', '**To Reproduce**'];
            const body = issue.body || '';
            const missing = required.filter(r => !body.includes(r));
            if (missing.length) {
              core.setFailed(`Issue is missing required sections: ${missing.join(', ')}`);
            }
